tier4/t4-devkit

t4_devkit/common/converter.py, t4_devkit/dataclass/box.py, t4_devkit/dataclass/label.py, t4_devkit/dataclass/pointcloud.py, t4_devkit/dataclass/roi.py, t4_devkit/dataclass/shape.py, t4_devkit/dataclass/trajectory.py, t4_devkit/dataclass/transform.py, t4_devkit/filtering/parameter.py, t4_devkit/schema/serialize.py, t4_devkit/schema/tables/attribute.py, t4_devkit/schema/tables/base.py, t4_devkit/schema/tables/calibrated_sensor.py, t4_devkit/schema/tables/category.py, t4_devkit/schema/tables/ego_pose.py, t4_devkit/schema/tables/instance.py, t4_devkit/schema/tables/keypoint.py, t4_devkit/schema/tables/log.py, t4_devkit/schema/tables/map.py, t4_devkit/schema/tables/object_ann.py, t4_devkit/schema/tables/registry.py, t4_devkit/schema/tables/sample.py, t4_devkit/schema/tables/sample_annotation.py, t4_devkit/schema/tables/sample_data.py, t4_devkit/schema/tables/scene.py, t4_devkit/schema/tables/sensor.py, t4_devkit/schema/tables/surface_ann.py, t4_devkit/schema/tables/visibility.py
`attrs` official documentation: https://www.attrs.org/en/stable/index.html.
=> refactor: replace `dataclasses` to `attrs`

t4_devkit/viewer/rendering_data/segmentation.py
This PR fixes runtime error during rendering segmentation image as follows:
```python
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/ktro2828/workspace/t4-devkit/t4_devkit/tier4.py", line 750, in render_scene
self._render_annotation_2ds(viewer, scene.first_sample_token, max_timestamp_us)
File "/home/ktro2828/workspace/t4-devkit/t4_devkit/tier4.py", line 1171, in _render_annotation_2ds
viewer.render_segmentation2d(
File "/home/ktro2828/workspace/t4-devkit/t4_devkit/viewer/viewer.py", line 247, in render_segmentation2d
segmentation_data.as_segmentation_image(),
File "/home/ktro2828/workspace/t4-devkit/t4_devkit/viewer/rendering_data/segmentation.py", line 65, in as_segmentation_image
return rr.SegmentationImage(data=image)
TypeError: …
```
=> fix: resolve runtime error with unexpected keyword

t4_devkit/schema/tables/ego_pose.py, t4_devkit/viewer/viewer.py
=> feat: add support of rendering geocoordinate

t4_devkit/dataclass/box.py, t4_devkit/dataclass/shape.py
Remark the order of box size as `(width, height, length)`.
=> fix: order of size

t4_devkit/dataclass/box.py, t4_devkit/dataclass/trajectory.py, t4_devkit/tier4.py, tests/conftest.py, tests/dataclass/test_box.py, tests/dataclass/test_trajectory.py, tests/dataclass/test_transform.py
This PR adds methods called `translate` and `rotate` to `Box3D` and `Trajectory` classes.
=> feat: add translate and rotate methods

t4_devkit/common/geometry.py
This PR resolves RuntimeError during invoking `view_points` with 3D box corners.
It should have been transposed from `(N, 3)` to `(3, N)`.
=> fix: resolve runtime error

t4_devkit/tier4.py
This PR updates Tier4 API to avoid runtime errors for irregular data as follows:
Case1:
Invalid instance token is contained in `object_ann`.
```shell
Creating data info for scene: 70891309-ca8b-477b-905a-5156ffb3df65
Traceback (most recent call last):
File "/workspace/tools/detection3d/create_data_t4dataset.py", line 290, in <module>
main()
File "/workspace/tools/detection3d/create_data_t4dataset.py", line 263, in main
t4 = Tier4(
File "/opt/conda/lib/python3.10/site-packages/t4_devkit/tier4.py", line 128, in __init__
self.__make_reverse_index__(verbose)
File "/opt/conda/lib/python3.10/site-packages/t4_devkit/tier4.py", line 189, in __make_reverse_index__
instance: Instance = self.get("instance", record.instance_token)
File "/opt/conda/lib/python3.10/site-packages/t4_devkit/tier4.py", …
```
=> refactor: update Tier4 API to avoid runtime errors for irregular data

docs/apis/common.md, t4_devkit/common/serialize.py, t4_devkit/schema/serialize.py, t4_devkit/schema/tables/base.py, t4_devkit/schema/tables/log.py, t4_devkit/schema/tables/object_ann.py, t4_devkit/schema/tables/sample.py, t4_devkit/schema/tables/sample_annotation.py, t4_devkit/schema/tables/sample_data.py, t4_devkit/schema/tables/sensor.py, t4_devkit/schema/tables/surface_ann.py
This PR introduces following changes:
- Add a function to serialize dataclasses defined by `attrs`, which is called `serialize_dataclass`.
- The internal works of `serialize_schema` is replaced by `serialize_dataclass`.
- By this change, no need to use `shortcuts` methods anymore, then they are removed.
=> feat(dataclass): add serialization function

t4_devkit/schema/name.py, t4_devkit/schema/tables/sample_data.py, t4_devkit/schema/tables/sensor.py, t4_devkit/schema/tables/vehicle_state.py, t4_devkit/schema/tables/visibility.py
This PR uses `@unique` decorator in order to ensure enum members are unqiue.
=> refactor: ensure enum members are unique

t4_devkit/filtering/compose.py, t4_devkit/filtering/functional.py, tests/fitering/test_filter_function.py
Rename filtering function from `FilterByAre` to `FilterByRegion`.
=> refactor: rename FilterByAre to FilterByRegion

t4_devkit/dataclass/transform.py, t4_devkit/viewer/viewer.py
=> style: update docstrings

t4_devkit/tier4.py, t4_devkit/viewer/__init__.py, t4_devkit/viewer/geography.py, t4_devkit/viewer/viewer.py
This PR introduces rendering geometric coordinates from the global map origin and ego position at the particular timestamp even if `EgoPose.geocoordinate` is `None`.
The global map origin is parsed from `map/global_map_center.pcd.yaml` if it is contained.
The expected format of `global_map_center.pcd.yaml` is as follows:
```yaml
/**:
ros__parameters:
map_origin:
latitude: 35.223124955115864
longitude: 138.80245834628386
elevation: 0.0
roll: 0.0
pitch: 0.0
yaw: 0.0
```
=> feat(visualize): add support of loading global map origin from yaml

.github/workflows/build-and-test.yaml
This PR introduces Github Actions workflow called `dorny/paths-filter` instead of builtin `paths-ignore` in order to allow to pass CI if modified files are not included in unit test targets.
=> ci: apply paths-filter instead of paths-ignore

t4_devkit/viewer/rendering_data/segmentation.py
This PR fixes runtime error during rendering segmentation images as follows:
```shell
[2025-02-11T05:27:45Z ERROR wgpu_core::device::global] Device::create_texture error: Dimension Y is zero
[2025-02-11T05:27:45Z ERROR wgpu_core::device::global] Texture::create_view(Id(134,36,vk)) error: TextureId Id(134,36,vk) is invalid
[2025-02-11T05:27:45Z ERROR re_space_view_spatial::visualizers::utilities::textured_rect] Failed to create texture for "/map/base_link/CAM_BACK/segmentation": Failed to create class_id_colormap.
[2025-02-11T05:27:45Z ERROR wgpu_core::device::global] Device::create_texture error: Dimension Y is zero
[2025-02-11T05:27:45Z ERROR wgpu_core::device::global] Texture::create_view(Id(89,61,vk)) error: TextureId Id(89,61,vk) is invalid
[2025-02-11T05:27:45Z WARN …
```
=> fix: avoid error during rendering segmentation image

docs/tutorials/cli.md, mkdocs.yaml, pyproject.toml, t4_devkit/cli/visualize.py
This PR introduces a CLI tool to visualize T4 dataset.
```shell
$ t4viz --help
Usage: t4viz [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
instance    Visualize a particular instance in a corresponding scene
pointcloud  Visualize pointcloud in a corresponding scene.
scene       Visualize a specific scene.
```
```shell
$ t4viz scene --help
Usage: t4viz scene [OPTIONS] DATA_ROOT
Visualize a specific scene.
Options:
-f, --future FLOAT Future time seconds.
-o, --output PATH  Output directory to save recoding .rrd file.
--no-show          Indicates whether not to show viewer.
--help             Show this message and exit.
```
```shell
$ t4viz instance --help
Usage: t4viz instance [OPTIONS] DATA_ROOT INSTANCE
Visualize a particular instance in a corresponding …
```
=> feat: add CLI tool for visualization

t4_devkit/dataclass/box.py, t4_devkit/dataclass/trajectory.py, tests/dataclass/test_box.py
This PR modifies dataclass fields as being included in initialization parameters.
This PR prevents that they are not serialized even if they have specific value.
=> feat: update initialization settings of  dataclass field 

t4_devkit/dataclass/box.py, t4_devkit/dataclass/trajectory.py, t4_devkit/helper/timeseries.py, t4_devkit/tier4.py, t4_devkit/viewer/rendering_data/box.py, tests/conftest.py, tests/dataclass/test_trajectory.py
This PR introduces `timestamps` attribute to the `Trajectory` dataclass.
Moreover, this PR includes separating `Trajectory` class into `Future` and `Past` classes.
Note that `Future` class consists of the `waypoints` in the shape of `(M, Tf, D), where `M` is the number of modes, `Tf` is the number of future timestamps.
However, `Past` class consists of the waypoints in the shape of `(1, Tp, D)`, where `Tp` is the number of past timestamps.
=> feat: add timestamps attribute to trajectory dataclass

docs/tutorials/customize.md, t4_devkit/common/serialize.py, t4_devkit/schema/serialize.py, tests/schema/tables/test_attribute_table.py, tests/schema/tables/test_calibrated_sensor_table.py, tests/schema/tables/test_category_table.py, tests/schema/tables/test_ego_pose_table.py, tests/schema/tables/test_instance_table.py, tests/schema/tables/test_log_table.py, tests/schema/tables/test_map_table.py, tests/schema/tables/test_object_ann_table.py, tests/schema/tables/test_sample_annotation_table.py, tests/schema/tables/test_sample_data_table.py, tests/schema/tables/test_sample_table.py, tests/schema/tables/test_sensor_table.py, tests/schema/tables/test_surface_ann_table.py, tests/schema/tables/test_vehicle_state_table.py, tests/schema/tables/test_visibility_table.py
This PR add new function called `serialize_dataclasses` which serializes list of attrs' dataclasses.
Also, this PR makes old functions, called `serialize_schema` and `serialize_schemas`, as **depreacated**.
=> feat: replace serialize functions

tests/conftest.py, tests/viewer/conftest.py
This PR adds option for pytest whether to spawn viewer.
```shell
pytest --spawn-viewer
```
=> test: add option whether to spawn viewer

t4_devkit/evaluation/dataset.py
This PR exchanges frame name of `ego2map` in loaded ground truths.
=> fix: source and destination frame name of ego2map

t4_devkit/viewer/record/box.py
This PR fixes the issue that future trajectories are visualized missing their origin.
Before
After
=> fix: append origin of trajectory

t4_devkit/helper/rendering.py, t4_devkit/tier4.py
This PR contributes to the speed up of the rendering processes by replacing asynchronous operations to multiprocessing.
|            | scene        | pointcloud |
|----------|---------------|------------------|
|Before| 0m3.797s | 1m2.000s    |
|After   | 0m2.789s | 0m49.222s |
=> perf: use concurrent instead of coroutine

pyproject.toml, t4_devkit/schema/tables/object_ann.py, t4_devkit/schema/tables/surface_ann.py
The validator will fail when our mask value is `null`, this PR fixes that by allowing passing `None` value` in `mask`.
=> fix: Fix an error when converting null masks in object_ann and surface_ann

t4_devkit/helper/rendering.py
As of https://github.com/tier4/t4-devkit/pull/143, it is allowed that `mask` field in `ObjectAnn/SurfaceAnn` is None.
To avoid runtime exception, this PR updates to skip operations handing mask in these cases.
=> fix: skip appending mask annotation if it is None

t4_devkit/dataclass/box.py, t4_devkit/tier4.py, tests/conftest.py
This PR introduces loading annotated 3D box's visibility.
=> feat: load 3D box visibility from dataset

t4_devkit/dataclass/box.py, t4_devkit/filtering/compose.py, t4_devkit/filtering/functional.py, t4_devkit/filtering/parameter.py, t4_devkit/schema/tables/visibility.py, tests/conftest.py, tests/fitering/test_filter_compose.py, tests/fitering/test_filter_function.py
This PR adds filtering function using box visibility.
=> feat: add filter class with box visibility

docs/apis/common.md, docs/tutorials/cli.md, pyproject.toml, t4_devkit/cli/sanity.py, t4_devkit/cli/version.py, t4_devkit/cli/visualize.py, t4_devkit/common/sanity.py
This PR adds CLI that performs sanity check and reports exceptions and warnings encountered while loading T4 dataset.
```shell
$ t4sanity <DATA_ROOT>
>>> Sanity checking...: 97it [00:03, 26.60it/s]
+--------------------------------------+---------+------------------------------------------------------------------------------------------------+
|              DatasetID               | Version |                                            Message                                             |
+--------------------------------------+---------+------------------------------------------------------------------------------------------------+
| 96200480-ae59-44cb-9e4e-dd9021e250e8 |    2    | bbox must be (xmin, ymin, xmax, ymax) and xmin <= xmax && ymin <= ymax: (1671, 198, 1440, 229) |
| …
```
=> feat: add CLI for sanity check

docs/tutorials/cli.md, docs/tutorials/cli/index.md, docs/tutorials/cli/t4sanity.md, docs/tutorials/cli/t4viz.md, docs/tutorials/customize.md, docs/tutorials/render.md, mkdocs.yaml
This PR updates the documentation of the CLI section.
=> docs: update CLI documentation

docs/tutorials/initialize.md, docs/tutorials/render.md, t4_devkit/cli/visualize.py, t4_devkit/common/sanity.py, t4_devkit/helper/rendering.py, t4_devkit/tier4.py
This PR adds support of loading T4 dataset metadata including dataset ID and version.
Note that **the parameter of initializing `Tier4` class is changed from this PR as below.**
Now, we have the following dataset structure:
```shell
dataset1
└── 0
├── annotation
├── data
...
```
Then you can initialize 
```python
>>> from t4_devkit import Tier4
>>> t4 = Tier4("dataset1")
>>> t4.data_root
"dataset1/0"
>>> t4.dataset_id
"dataset1"
>>> t4.version
"0"
```
It is also allowed to load T4 dataset without version directory, then `version` returns `None`:
```shell
dataset2
├── annotation
├── data
...
```
```python
>>> from t4_devkit import Tier4
>>> t4 = Tier4("dataset1")
>>> t4.data_root
"dataset1"
>>> t4.dataset_id
"dataset1"
>>> t4.version
None
```
=> feat!: add support of loading dataset metadata

docs/tutorials/cli/t4sanity.md, docs/tutorials/initialize.md, t4_devkit/cli/sanity.py, t4_devkit/cli/visualize.py, t4_devkit/common/sanity.py, t4_devkit/tier4.py
This PR allows users to load the specific version of the dataset by using `revision: str` parameter.
In the construction of `Tier4` class, you can specify `revision: str` as follows:
```python
from t4_devkit import Tier4
t4 = Tier4("data/t4", revision="2")
```
If you doesn't specify `revision`, it searches the latest one.
=> feat: enable to load a specific version of the dataset

docs/tutorials/cli/t4sanity.md, t4_devkit/cli/sanity.py, t4_devkit/common/sanity.py, t4_devkit/tier4.py
This PR adds `DBStatus` enum to `DBException` for displaying status information.
This is used in `t4sanity` command.
In the case of any exceptions occurred:
```shell
>>>Sanity checking...: 2it [00:00, 18.61it/s]
⚠️  Encountered some exceptions!!
+--------------------------------------+---------+--------+------------------------------------------------------------------------------------------------+
|              DatasetID               | Version | status |                                            Message                                             |
+--------------------------------------+---------+--------+------------------------------------------------------------------------------------------------+
| 4ea652e7-76d5-4240-adb5-9d4ecac25eae |    2    | ERROR  | bbox must be (xmin, …
```
=> feat: add DB status

t4_devkit/schema/tables/sample_data.py, tests/schema/conftest.py
This pull request introduces a minor schema update to the `SampleData` class in `t4_devkit/schema/tables/sample_data.py` to support tracking additional metadata for each sample. The most important change is the addition of a new field for storing the relative path to associated metainfo data.
Schema enhancements:
* Added a new string field `info_filename` to the `SampleData` class, which stores the relative path to metainfo data-blobs on disk. This field is now part of both the docstring and the class definition, with a default value of an empty string and appropriate type validation. [[1]](diffhunk://#diff-3e4c8c2231dc13b0f359ea2508d1040e71f524d3382d8e83225f5a3e43b6fecaR87) [[2]](diffhunk://#diff-3e4c8c2231dc13b0f359ea2508d1040e71f524d3382d8e83225f5a3e43b6fecaR107)
This field will point …
=> feat: add info_filename field to sample_data table

README.md, docs/index.md, docs/schema/data.md, docs/schema/index.md, docs/schema/table.md, mkdocs.yaml
This PR updates the document for T4 dataset schema definitions.
These updates are basically moved from [tier4_perception_dataset/docs/t4_format_3d_defailed.md](https://github.com/tier4/tier4_perception_dataset/blob/main/docs/t4_format_3d_detailed.md).
You can check the preview of the document on your local device as follows:
```shell
mkdocs serve
```
=> docs: update document for dataset schema

t4_devkit/tier4.py
This PR adds property of the path to directories included in T4 dataset, such as `map` and `input_bag`.
=> feat: add directory path as property

t4_devkit/tier4.py
This PR removes `Tier4.__load_table__(...)` method and define as function called `load_table(...)`.
=> refactor: define the method to load tables as function

t4_devkit/dataclass/box.py, t4_devkit/dataclass/trajectory.py, t4_devkit/dataclass/transform.py, t4_devkit/viewer/geography.py
This PR updates typing to ensure that the input is correct.
=> style: update typing

t4_devkit/helper/rendering.py
This pull request improves the performance of annotation rendering in the `t4_devkit/helper/rendering.py` module by parallelizing the rendering of 2D and 3D annotations. The main change is the use of the executor to submit annotation rendering tasks concurrently, which should result in faster rendering times for both scenes and instances.
Performance improvements in annotation rendering:
* In the `render_scene` method, the calls to `_render_annotation3ds` and `_render_annotation2ds` are now submitted to `self._executor` for parallel execution, allowing these tasks to run concurrently and speeding up the rendering process.
* In the `render_instance` method, the annotation rendering tasks (`_render_annotation3ds` and `_render_annotation2ds`) are also submitted in parallel using …
=> perf: execute annotation rendering in parallel

t4_devkit/helper/rendering.py, t4_devkit/viewer/color.py, t4_devkit/viewer/viewer.py
This pull request introduces a new color mapping system for point cloud visualization, improving flexibility and maintainability. The main change is the addition of a `PointCloudColorMode` enum and a `pointcloud_color` function, allowing selection of color modes (distance or intensity) when rendering point clouds. The viewer now uses this new system instead of directly calculating distance-based colors.
**Point cloud color mapping improvements:**
* Added a `PointCloudColorMode` enum to define selectable color modes for point cloud visualization, supporting both distance and intensity modes. (`t4_devkit/viewer/color.py`)
* Implemented a new `pointcloud_color` function that returns color maps based on the selected color mode, improving extensibility and code clarity. …
=> feat: add support of rendering point cloud coloring with intensity

.github/workflows/deploy-document.yaml
This pull request updates the deployment workflow for documentation to support versioned releases and aliases. It adds support for deploying documentation on tag pushes and allows specifying version and alias information via workflow dispatch inputs. The deployment logic now uses the `mike` tool for managing multiple documentation versions.
**Workflow trigger and input enhancements:**
* The workflow now triggers on both pushes to `main` and tags matching the pattern `v*`, and supports manual dispatch with inputs for version and alias.
**Deployment logic improvements:**
* Added a step to determine the version and alias based on the event type (push, tag, or workflow dispatch), and outputs these for use in subsequent steps.
* Replaced the previous `mkdocs gh-deploy` command with `mike …
=> ci: add support of versioning documents

mkdocs.yaml
This pull request makes a small configuration update to the `mkdocs.yaml` file. The change adds the `mike` plugin with the `version_selector` option enabled, which allows users to select documentation versions in the site.
=> docs: add version selector for mike
