tier4/t4-devkit

- t4_devkit/viewer/rendering_data/segmentation.py
> fix: resolve rendering segmentation

- docs/tutorials/render.md
- t4_devkit/tier4.py
- t4_devkit/viewer/viewer.py
- tests/viewer/conftest.py
- tests/viewer/test_viewer.py
This PR renames `Tier4Viewer` to `RerunViewer`.
> refactor: rename Tier4Viewer to RerunViewer

- pyproject.toml
Add `required-imports` to the ruff rules.
> chore: update required imports

- t4_devkit/viewer/rendering_data/box.py
- t4_devkit/viewer/rendering_data/segmentation.py
This PR introduces displaying shorter uuid length in 6.
> refactor: make shorter the uuid length

- t4_devkit/tier4.py
This PR introduces rendering a particular 2D instance with `Tier4.render_instance(...)`.
> feat: add support of rendering specified 2d instance

- pyproject.toml
> chore: add dependencies

- t4_devkit/viewer/rendering_data/box.py
This PR introduces 3D box fill mode as `solid` by default.
> feat: set 3d box fill mode to solid by default

- docs/tutorials/cli.md
- docs/tutorials/render.md
- t4_devkit/cli/visualize.py
- t4_devkit/helper/rendering.py
- t4_devkit/tier4.py
This PR allows us to specify any number of instances in rendering instance.
With `t4viz`, for example:
```shell
t4viz instance <DATA_ROOT> <INSTANCE1> <INSTANCE2> ... [OPTION]
```
> feat: add support of specifying multiple instances

- docs/tutorials/customize.md
This PR updates the document for schema class customization.
> docs: update document for schema customization

- t4_devkit/helper/timeseries.py
- t4_devkit/tier4.py
> fix: fix typo

- t4_devkit/common/validator.py
- t4_devkit/dataclass/box.py
- t4_devkit/dataclass/label.py
- t4_devkit/dataclass/roi.py
- t4_devkit/dataclass/trajectory.py
- t4_devkit/dataclass/transform.py
- t4_devkit/filtering/parameter.py
- t4_devkit/schema/tables/attribute.py
- t4_devkit/schema/tables/base.py
- t4_devkit/schema/tables/calibrated_sensor.py
- t4_devkit/schema/tables/category.py
- t4_devkit/schema/tables/ego_pose.py
- t4_devkit/schema/tables/instance.py
- t4_devkit/schema/tables/keypoint.py
- t4_devkit/schema/tables/log.py
- t4_devkit/schema/tables/map.py
- t4_devkit/schema/tables/object_ann.py
- t4_devkit/schema/tables/sample.py
- t4_devkit/schema/tables/sample_annotation.py
- t4_devkit/schema/tables/sample_data.py
- t4_devkit/schema/tables/scene.py
- t4_devkit/schema/tables/sensor.py
- t4_devkit/schema/tables/surface_ann.py
- t4_devkit/schema/tables/vehicle_state.py
- t4_devkit/schema/tables/visibility.py
- tests/common/test_validator.py
- tests/dataclass/test_trajectory.py
- tests/viewer/test_viewer.py
This PR introduces validators for dataclass fields.
This PR relates to https://github.com/tier4/t4-devkit/issues/115
> feat: add dataclass field validator

- pyproject.toml
This PR bumps version from v0.0.9 to v0.0.10
> chore: bump to v0.0.10

- docs/tutorials/cli.md
- pyproject.toml
- t4_devkit/cli/visualize.py
This PR styles terminal color and format in CLI as follows:
```shell
$ t4viz -h
Usage: t4viz [OPTIONS] COMMAND [ARGS]...
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --version             -v        Show the application version and exit.                                           │
│ --install-completion            Install completion for the current shell.                                        │
│ --show-completion               Show completion for the current shell, to copy it or customize the installation. │
│ --help                -h        Show this message and exit.                                                      │
╰───────────────────────────────────────────────────────────────────────────────────────────── …
```
> feat: rich CLI console

- pyproject.toml
This PR bumps version from v0.0.10 to v0.0.11
> chore: bump to v0.0.11

- t4_devkit/viewer/rendering_data/box.py
This PR fixes changing future linestrip color in the wrong.
Before
[Screencast from 05-08-2025 07:01:17 PM.webm](https://github.com/user-attachments/assets/e20e0642-9390-4d16-b8e0-abaf33b23cd8)
After
[Screencast from 05-08-2025 06:58:54 PM.webm](https://github.com/user-attachments/assets/434943ca-bb19-4db7-a8e6-5e61336befc0)
> fix: resolve changing linestrip color in the wrong

- t4_devkit/evaluation/__init__.py
- t4_devkit/evaluation/dataset.py
This PR adds a simple dataset loader and classes to represent ground truth.
> feat: add ground truth class

- t4_devkit/evaluation/result/box.py
- tests/evaluation/result/test_box_match.py
This PR adds the attribute called `ego2map` to `FrameBoxMatch`.
> feat: add ego2map attribute to FrameBoxMatch

- t4_devkit/evaluation/matching/parameter.py
- t4_devkit/evaluation/matching/scorer.py
- t4_devkit/evaluation/metric/__init__.py
- t4_devkit/evaluation/metric/ap.py
This PR adds average precision class for detection metric.
> feat: add average precision metric

- t4_devkit/evaluation/metric/__init__.py
- t4_devkit/evaluation/metric/clear.py
- t4_devkit/evaluation/result/box.py
This PR adds tracking metric called CLEAR, which computes MOTA and MOTP.
> feat: add CLEAR metric for tracking evaluation

- pyproject.toml
This PR bumps version from v0.0.11 to v0.0.12.
> chore: bump to v0.0.12

- pyproject.toml
This PR bumps the version from v0.0.12 to v0.0.13.
> chore: bump to v0.0.13

- pyproject.toml
This PR bumps the version from v0.0.14 to v0.1.0
> chore: bump to v0.1.0

- pyproject.toml
This PP bumps the version from v0.2.0 to v0.2.1.
> chore: bump to v0.2.1

- README.md
- docs/index.md
This PR updates README by adding link to the dataset schema document.
> docs: update README

- pyproject.toml
This pull request makes a minor update to the project version in the `pyproject.toml` file, incrementing it from `0.2.1` to `0.3.0`. No other changes are included.
([pyproject.tomlL7-R7](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7))
> chore: bump to v0.3.0

- pyproject.toml
This pull request makes a small change to the development dependencies in `pyproject.toml` by adding the `mike` package. This will help manage versioned documentation deployments.
* Added `mike>=2.1.3` to the `dev` dependencies in `pyproject.toml` to support versioned documentation.
> chore(deps): add mike to development dependencies
